In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3])

In [3]:
x.__class__

numpy.ndarray

In [4]:
x.shape

(3,)

In [5]:
x.ndim

1

In [6]:
W = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
W.shape

(2, 3)

In [8]:
W.ndim

2

In [9]:
X = np.array([[0, 1, 2], [3, 4, 5]])

In [10]:
W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [11]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [12]:
A = np.array([[1, 2], [3, 4]])

In [13]:
A * 10

array([[10, 20],
       [30, 40]])

In [14]:
b = np.array([10, 20])

In [15]:
A * b

array([[10, 40],
       [30, 80]])

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

32

In [17]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [18]:
x = np.random.randn(10, 2)
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
h = np.dot(x, W1) + b1

In [19]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [20]:
a = sigmoid(h)
W2 = np.random.randn(4, 3)
b2 = np.random.randn(3)
s = np.dot(a, W2) + b2

In [25]:
class Sigmoid:
    def __init__(self):
        self.params = []
        
    def forward(self, x):
        return 1 / (1 + np.exp(-x))

In [26]:
class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
        
    def forward(self, x):
        W, b = self.params
        out =  np.dot(x, W) + b
        return out

In [27]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size
        
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)
        
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]
        
        self.params = []
        for layer in self.layers:
            self.params += layer.params
    
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x

In [28]:
x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)

In [29]:
s

array([[1.10504151, 0.71986794, 0.1833115 ],
       [1.07225728, 0.58124947, 0.28300391],
       [1.20154088, 0.63529903, 0.0595674 ],
       [0.62392475, 0.54546954, 0.65106338],
       [1.1014362 , 0.7085526 , 0.17895842],
       [1.02103323, 0.50225118, 0.41117563],
       [1.14024069, 0.6879545 , 0.13775904],
       [0.49901314, 0.59644193, 0.7023256 ],
       [1.08418534, 0.64920861, 0.20798444],
       [1.03086721, 0.53506223, 0.41892286]])

In [30]:
D, N = 8, 7
x = np.random.randn(N, D)
y = np.sum(x, axis=0, keepdims=True)
dy = np.random.randn(1, D)
dx = np.repeat(dy, N, axis=0)

In [51]:
class MatMul:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros.like(W)]
        self.x = None
        
    def forward(self, x):
        W, = self.params
        dx = np.dot(x, W)
        self.x = x
        return out
    
    def backward(self, dout):
        W, = self.params
        dx = np.dot(dout, W.T)
        dw = np.dot(self.x.T, dout)
        self.grads[0][...] = dw
        return dx
    
class Sigmoid:
    def __init_(self):
        self.params, self.grads = [], []
        self.out = None
    
    def forward(self, x):
        out = 1 / (1 + np.exp(-x))
        self.out = out
        return out
    
    def backward(self, dout):
        dx = dout * (1.0 * self.out) * self.out
        return dx

class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
        self.grads = [np.zeros.like(W), np.zeros_like(b)]
        self.x = None
        
    def forward()
        
        