In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3])

In [3]:
x.__class__

numpy.ndarray

In [4]:
x.shape

(3,)

In [5]:
x.ndim

1

In [6]:
W = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
W.shape

(2, 3)

In [8]:
W.ndim

2

In [9]:
X = np.array([[0, 1, 2], [3, 4, 5]])

In [10]:
W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [12]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [15]:
A = np.array([[1, 2], [3, 4]])

In [16]:
A * 10

array([[10, 20],
       [30, 40]])

In [17]:
b = np.array([10, 20])

In [18]:
A * b

array([[10, 40],
       [30, 80]])

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

32

In [23]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [24]:
x = np.random.randn(10, 2)
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
h = np.dot(x, W1) + b1

In [25]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [27]:
a = sigmoid(h)
W2 = np.random.randn(4, 3)
b2 = np.random.randn(3)
s = np.dot(a, W2) + b2

In [28]:
class Sigmoid:
    def __init__(self):
        self.params = []
        
    def forward(self, x):
        return 1 / (1 + np.exp(-x))

In [34]:
class Affine:
    def __init__(self, W, b):
        self.params = [W, b]
        
    def forward(self, x):
        W, b = self.params
        out =  np.dot(x, W) + b
        return out

In [47]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size
        
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)
        
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]
        
        self.params = []
        for layer in self.layers:
            self.params += layer.params
    
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x

In [48]:
x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)

In [49]:
s

array([[-1.69028685,  0.3819114 ,  0.37101352],
       [-1.16318447,  0.46639557, -0.57490742],
       [-1.16001876,  0.24149061,  0.07246004],
       [-1.43036134,  0.55217458, -0.75523155],
       [-1.13936974,  0.37246677, -0.36073681],
       [-1.58794187,  0.31982533,  0.30008614],
       [-1.15393346,  0.277774  , -0.09885104],
       [-1.11175518,  0.37454993, -0.3721453 ],
       [-1.31441944,  0.35102259, -0.29109761],
       [-1.56491825,  0.31355693, -0.17932848]])

In [50]:
D, N = 8, 7
x = np.random.randn(N, D)
y = np.sum(x, axis=0, keepdims=True)
dy = np.random.randn(1, D)
dx = np.repeat(dy, N, axis=0)

In [51]:
class MatMul:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros.like(W)]
        self.x = None
        
    def forward(self, x):
        W, = self.params
        dx = np.dot(x, W)
        self.x = x
        return out
    
    def backward(self, dout):
        